### ISSUE TITLE
Documentation is wrong, this tool is correct: `json_key_base64` vs. `_json_key_base64` 

### ISSUE THREAD

**Issue by ari-becker** [GoogleCloudPlatform/artifact-registry-go-tools#18]
Not sure how to open a documentation bug, but this tool is correct, hopefully whoever works on this tool can forward it to the documentation team 🙏 

Correct code sets `.netrc` with `login` to `_json_key_base64`: https://github.com/GoogleCloudPlatform/artifact-registry-go-tools/blob/52865e136f694d84edc386a6f04ceeb43d8a26b0/pkg/netrc/netrc.go#L40

Documentation sets `.netrc` with `login` to `json_key_base64`: https://cloud.google.com/artifact-registry/docs/go/authentication#authenticating_with_a_service_account_key 

Trying `json_key_base64` resulted in `401 Unauthorized` errors and lots of head-scratching.

The documentation should be fixed to show `_json_key_base64`.

**Comment by yihanzhen** [comment]
The fix has been submitted.
