### ISSUE TITLE
Authenticate using Auth-Token

### ISSUE THREAD

**Issue by weigert** [GoogleCloudPlatform/artifact-registry-go-tools#9]
Hello,

I am building a docker-container to compile and run a standard go program, which utilizes a module located in a private artifact-registry go repository. The docker build is executed with cloud-build using a repository-push trigger, meaning that all data required for the build should be located exclusively inside the repository.

I can't find a good way to authenticate to artifact-registry from within the docker-container using `artifact-registry-go-tools`.

**The issue**

In order to authenticate to the gcloud artifact registry _at build time_ within the docker-container, I **must** copy a json_key into the container (i.e. I can't use a volume mount to get ADC). This is fine for a multi-stage build, as it would be discarded from the container itself, but I don't want the json_key _inside the repository_ at all.

Dockerfile:

```Dockerfile
FROM golang:alpine AS builder

RUN apk --no-cache add git
COPY . /build/

ENV GOPROXY="https://LOCATION-go.pkg.dev/PROJECT_ID/REPOSITORY_NAME,https://proxy.golang.org,direct"
ENV GONOSUMDB="MY_DOMAIN/*"
ENV GONOPROXY=github.com/GoogleCloudPlatform/artifact-registry-go-tools

# CRITICAL SECTION
RUN GOPROXY=proxy.golang.org go run github.com/GoogleCloudPlatform/artifact-registry-go-tools/cmd/auth@latest \
      add-locations --locations=LOCATION \
      --json_key=some_account_key_inside_the_docker_context_root_i.e._repository.json

WORKDIR /build/
RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -a -o app main.go

FROM alpine:latest
RUN apk --no-cache add ca-certificates

WORKDIR /app/
COPY --from=builder /build/app ./
EXPOSE 8080
ENTRYPOINT ["./app"]
```

I can't use `buildkit` to provide another build-context containing the ADC from outside the repository, as I get the following error:
https://www.docker.com/blog/dockerfiles-now-support-multiple-build-contexts/
```
--build-context test="~/.config/gcloud"
```
```
failed to get build context test: stat ~/.config/gcloud: no such file or directory
```

It is possible to use `go mod vendor` to fetch the dependencies locally in an authenticated environment and ship them in the repository, but I would prefer it if I didn't maintain local copies all the time and every trigger of cloudbuild would fetch the latest dependencies automatically. Cloudbuild still couldn't update the vendor files automatically, unless I authenticate!!!

Finally, I could use the cloudbuild secret manager but it would have to contain the entire json_key file, and then pass this into the container using an environment variable, which then extracts it again into the file to pass into `artifact-registry-go-tools`.

**The Question**

Could it be possible to pass a raw auth token to the artifact-registry-go-tools instead of a json_key, so that I could set an environment variable using e.g. `$(gcloud auth print-access-token)`? I believe this would be a more elegant method.

This way, my local build could define an access token easily using gcloud auth, and I could get the access token in cloudbuild easily using the secret manager interface in cloudbuild.

If you have other suggestions, I would be glad to hear them.

**Comment by lindsayismith** [comment]
+Hanzhen Yi ***@***.***>  +kavala-team ***@***.***>

Hi Nick, apologies for the delay in responding.  I've included Hanzhen on
the thread as he is the author of artifact-regsitry-go-tools.

I don't completely follow all the phases of your build here - e.g.
Cloud Build, the DockerFile or equivalent docker container build, and the
actual running of the container.

However I think I understand what you're asking for. The authentication
plugin currently does the following, in order:

1. Uses the google auth libraries to look for ADC.  This will look at the
GOOGLE_APPLICATION_CREDENTIALS environment var for a json key, then will
try getting a token from the metadata service (in the case of GCE VM) etc.
2. It will fall back to running gcloud to get an auth token

I think what you're asking is if the plugin could also directly support
looking for an auth token from an environment variable, e.g. if there is a
var named, say 'ARTIFACT_REGISTRY_TOKEN', it would expect the value to be
the equivalent of (gcloud auth print-access-token) and pass it directly to
AR.

Is this correct?

**Comment by yihanzhen** [comment]
@weigert If you are building on GCB can you try leaving the flag `--json_key` as empty? the auth tool should then look up Application Default Credentials (ADC) and will eventually use the credentials of the GCB service account. 

We could add an additional flag to let the caller pass in the auth token, but I think if ADC works here (no so sure since you are within a docker image) it's the easiest way.

**Comment by weigert** [comment]
@yihanzhen thanks for the response. I will try to be slightly more specific

I am building locally with buildkit and remotely with GCB. This is a multi-platform build (hence buildkit), which is why the golang binary has to be compiled _inside_ the docker container, not simply mounted. This means that authentication is required _inside_ the container (or alternatively: shipping with `go mod vendor`, which I don't want).

The issue is that I can't get ADC into the container using a volume mount at build time (i.e. to compile the container), only at runtime. Therefore, any credentials have to be inside the Dockerfile build root, which means having a service account key in my repository (or passed in through secret manager, but only on GCB, not locally).

So, sadly, ADC can't be made available inside the Docker container, and getting the json_key in instead is rather cumbersome and can lead to a discrepancy between local and remote builds.

Alternatively, if I can use a simple auth token with the registry tools, then I can pass this into the container as an environment variable at build-time easily locally _and_ in the cloud, authenticate to my private registry and have a uniform multi-platform build system with GCB within the docker container.

In effect this means that a multi-platform build of a docker container running a go binary, which uses dependencies in a private GCP artifact-registry, would be much simpler and would not require insecure storage of service-account-keys in the repo or an inconsistent build between GCB and local by using the secret manager.

I hope this makes sense!

**Comment by weigert** [comment]
Since posting this though, I had thought of an alternative solution, which is to utilize `go mod vendor` in a preceding cloudbuild step to make the dependencies available to the Dockerfile build root that way. This is effectively the "safe" workaround, and lets you authenticate outside of the docker container, circumventing the issue. Then you add the vendor-files to your `.gitignore` and you can do the same locally. You just need to make sure to refresh them explicitly every time you build.

Still, it's good to note that authenticating with ADC at build-time for a go container with private GAR dependencies is currently not possible (but would be with a token!), and using the `json_key` alternative is not trivial and potentially insecure if done naively.

**Comment by weigert** [comment]
Hi.

I would just like to note that the fix resolves my issue nicely.

Within the Dockerfile, one can now write:

```Dockerfile
#...
ARG GCP_AUTH_TOKEN
ENV GOPROXY="https://LOCATION-go.pkg.dev/PROJECT_ID/REPOSITORY_NAME,https://proxy.golang.org,direct"
ENV GONOSUMDB="MY_DOMAIN/*"
ENV GONOPROXY=github.com/GoogleCloudPlatform/artifact-registry-go-tools
RUN GOPROXY=proxy.golang.org go run github.com/GoogleCloudPlatform/artifact-registry-go-tools/cmd/auth@latest \
      add-locations --locations=LOCATION
RUN GOPROXY=proxy.golang.org \
               go run github.com/GoogleCloudPlatform/artifact-registry-go-tools/cmd/auth@latest refresh \
      --token ${GCP_AUTH_TOKEN}
#...
```

and can authenticate within the container at build time using:

```bash
docker build --build-arg GCP_AUTH_TOKEN="$(gcloud auth print-access-token)"
```

which is valid locally and in GCB.

Thanks again!

**Comment by lindsayismith** [comment]
Awesome, thanks for letting us know!
